[debug]
log_level = "critical"
address = "0.0.0.0"
port = 80
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5

[release]
log_level = "critical"
address = "0.0.0.0"
port = 80
workers = 24
keep_alive = 5
read_timeout = 5
write_timeout = 5

